---
title: Chapter 15. The FreeBSD Booting Process
part: Part III. System Administration
prev: books/handbook/config
next: books/handbook/security
description: An introduction to the FreeBSD Booting Process, demonstrates how to customize the FreeBSD boot process, including everything that happens until the FreeBSD kernel has started, probed for devices, and started init
tags: ["boot", "boot process", "device hints", "x86", "amd64", "MBR", "GPT", "UEFI", "bsdlabel", "boot0", "Single-User Mode", "Multi-User Mode"]
showBookMenu: true
weight: 19
params:
  path: "/books/handbook/boot/"
---

[[boot]]
= The FreeBSD Booting Process
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumoffset: 15
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/boot/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[boot-synopsis]]
== Synopsis

The process of starting a computer and loading the operating system is referred to as "the bootstrap process", or "booting".
FreeBSD's boot process provides a great deal of flexibility in customizing what happens when the system starts, including the ability to select from different operating systems installed on the same computer, different versions of the same operating system, or a different installed kernel.

This chapter details the configuration options that can be set.
It demonstrates how to customize the FreeBSD boot process, including everything that happens until the FreeBSD kernel has started, probed for devices, and started man:init[8].
This occurs when the text color of the boot messages changes from bright white (or bright multi-colored) to grey.

Read this chapter to learn:

* The components of the FreeBSD bootstrap system and how they interact.
* The options that can be passed to the components in the FreeBSD bootstrap in order to control the boot process.
* The basics of setting device hints.
* How to boot into single- and multi-user mode and how to properly shut down a FreeBSD system.

[NOTE]
====
This chapter only describes the boot process for FreeBSD running on x86 and amd64 systems.
====

[[boot-concepts]]
== Jargon and concepts

Turning on a computer and starting the operating system poses an interesting dilemma.
By definition, the computer does not know how to do anything until the operating system is started.
This includes running programs from the disk.
If the computer can not run a program from the disk without the operating system, and the operating system programs are on the disk, how is the operating system started?

This problem parallels one in the book The Adventures of Baron Munchausen.
A character had fallen part way down a manhole, and pulled himself out by grabbing his bootstraps and lifting.
In the early days of computing, the term _bootstrap_ was applied to the mechanism used to load the operating system.
It has since become shortened to "booting".

=== Firmware

The solution to the dilemma is that there are programs in _firmware_, which are run when the computer is turned on.
Firmware is non-volatile memory, which is not cleared when the machine is powered off.
On x86 and amd64 systems, there are two overall categories of firmware:

* The so-called Basic Input/Output System (BIOS) dates from the times of the IBM Personal Computer/AT (PC/AT).
* The Unified Extensible Firmware Interface (UEFI) was invented by Intel to address the many limitations and complexities of BIOS firmware that had become apparent over the following decade.

These firmware programs know enough about the disk to load some simple programs from some well-known locations there, and to then run them.
Those simple programs know more about the disk, and can load and run other programs.

=== Stages and boot records

Booting is thus described as a series of _stages_, each one loading and running the next until the operating system proper is loaded and running.

The exact number and purpose of the individual stages varies.
One of the several reasons that UEFI was invented was that the BIOS imposed draconian size limits on several of the bootstrap programs.
They had to fit into one _boot record_, a 512-byte disk sector, less the sizes of the other things that that record also contained.
This means that several stages needed a very small program, small enough to fit into such a disk sector, to load and run the rest of the code for that stage.

The term _boot record_ covers booting both from removable media, such as a floppy disk, and from fixed media, such as a hard disk.
The BIOS system loaded a _Volume Boot Record_ (VBR) from floppy disks, which also contained a BIOS Parameter Block (BPB).
It loaded a _Master Boot Record_ (MBR) from hard discs, which also contained part of the partition table.

A simple MBR boot program in its turn loaded a VBR from one individual disk partition.
More complex ones needed to load additional parts of themselves, containing code to do things like interact with the operator in less terse ways, and would then after that load a VBR from a disk partition.

=== boot managers

The BIOS system gained complexities from third-party _boot managers_, programs that allowed the operator to pick and choose which of several operating systems to boot when a computer had multiple operating systems installed.
Some examples of boot managers are IBM's Boot Manager that came with OS/2, the similar Boot Manager that came with Partition Magic, Microsoft's Windows Boot Manager, and the GNU Grand Unified Boot Manager (GRUB).

UEFI also contains a Boot Manager.
The Microsoft Windows Boot Manager, GRUB, and the EFI Boot Manager not only can pick and choose amongst operating systems, they can pass information to those operating systems, in the form of file pathnames, flags, and variables.

[NOTE]
====
This chapter does not cover any third-party Boot Managers that need additional software to be installed beyond FreeBSD itself.
// There is extref:{faq}[a frequently asked question] about GRUB. Beyond the answer there, //
Users of GRUB should refer to https://www.gnu.org/software/grub/grub-documentation.html[GNU-provided documentation].

The UEFI Boot Manager is included in the UEFI firmware itself.
FreeBSD comes with tools for working with it.
====

[[boot-introduction]]
== FreeBSD Boot Process

The FreeBSD boot process can take number of different forms.
Which form is used is determined by what firmware the machine has (UEFI or BIOS) and how its (boot) disk is partitioned (MBR or GPT).

The two main standards for disk partitioning are the older MBR partition table, and the newer GUID Partition Table (GPT).
GPT partitioning is often found on computers with UEFI firmware.
But that is not a requirement, and a GPT can even be used on machines with only an old BIOS.

[NOTE]
====
A third standard is the old BSD "disklabel" scheme.
This is no longer in common use, and is not covered by this chapter.
====

The forms converge at the point where a loader program loads and runs the FreeBSD kernel, its kernel modules, and some ancillary information.

The kernel is started by that loader and begins to probe for devices and initialize them for use.
Once the kernel boot procedure is finished, the kernel passes control to the user process man:init[8], which makes sure the disks are in a usable state, starts the user-level resource configuration which mounts file systems, sets up network cards to communicate on the network, and starts the processes which have been configured to run at startup.

=== On UEFI machines

On UEFI machines, FreeBSD bootstrap has just two stages to get as far as the kernel being up and running:

. The UEFI Boot Manager loads and runs the man:loader.efi[8] program from the EFI System Partition.
. The man:loader.efi[8] program loads and runs the FreeBSD kernel.

[NOTE]
====
There used to be an intermediate stage man:boot1.efi[8] program.
This is no longer required, and man:loader.efi[8] is now simply loaded directly.
====

To control where and how in the EFI Boot Manager the entry (or even entries) for FreeBSD appears, and in what order the EFI Boot Manager attempts to bootstrap things, use man:efibootmgr[8].

man:loader.efi[8] is put into place on the EFI System Partition by the FreeBSD installer.
To re-install it if that becomes necessary, simply copy it from the FreeBSD filesystem (where it exists as a file in the [.filename]#/boot# directory) to one of the several known locations where the UEFI Boot Manager expects it to be.

For example, supposing that the EFI System Partition is partition number 1 on device [.filename]#ada1#:
[source,shell]
....
# mount -t msdosfs /dev/ada1p1 /boot/efi
# cp /boot/loader.efi /boot/efi/efi/boot/BOOTX64.efi
# cp /boot/loader.efi /boot/efi/efi/freebsd/loader.efi
# umount /boot/efi
....

[NOTE]
====
The name [.filename]#EFI/FREEBSD/LOADER.EFI# is the FreeBSD conventional location for man:loader.efi[8] when UEFI booting from fixed storage devices.
The name [.filename]#EFI/BOOT/BOOTX64.EFI# is for amd64 systems when booting from removable storage devices.
The latter file has a different name on other processor architectures.
Refer to man:loader.efi[8] and man:uefi[8] to find the names of the architecture-specific files.

The `/boot/efi` mount point is described in man:hier[7].
====

=== On BIOS machines with GPT disks

On BIOS machines with GPT disks, there are more stages:

. The BIOS loads and runs the MBR from its well-known place on the first (according to the BIOS) disk.
. The MBR program reads the GUID Partition Table and looks for a partition of type `freebsd-boot`.
. The MBR program reads the entire `freebsd-boot` partition contents into memory and runs the whole thing as one program.
. The `freebsd-boot` program is either man:gptboot[8] or man:gptzfsboot[8].
.. man:gptboot[8] looks for man:loader[8] in the `boot` directory of a FreeBSD UFS partition, and loads and runs it.
.. man:gptzfsboot[8] looks for FreeBSD ZFS partitions, looks at their zpool(s), reads the `bootfs` property of the zpool, and loads and runs man:zfsloader[8] from the [.filename]#/boot# directory in the named ZFS dataset.
. The man:loader[8] or man:zfsloader[8] program loads and runs the FreeBSD kernel.

The programs here are put into place by the FreeBSD installer.
To re-install them manually if that becomes necessary, use the `bootstrap` subcommand of the man:gpart[8] command.
Copies of the programs exist in the FreeBSD filesystem as files in the [.filename]#/boot# directory.

For example, supposing that the first BIOS disk is device [.filename]#ada0#, the `freebsd-boot` partition is (GPT) partition number 1 on that disk, and FreeBSD proper is installed in a UFS partition:
[source,shell]
....
# gpart bootstrap -b /boot/pmbr ada0
# gpart bootstrap -p /boot/gptboot -i 1 ada0
....

For a second example, supposing that the first BIOS disk is device [.filename]#ada0#, the `freebsd-boot` partition is (GPT) partition number 1 on that disk, and FreeBSD proper is installed in a ZFS partition:
[source,shell]
....
# gpart bootstrap -b /boot/pmbr ada0
# gpart bootstrap -p /boot/gptzfsboot -i 1 ada0
....

[WARNING]
====
Do not use man:dd[1] to attempt to install these bootstrap programs.
Specialized copying procedures provided by GEOM are needed to ensure that writing the programs to disk does not overwrite ('protective MBR') partition tables.

Do not use man:fdisk[1] to attempt to install bootstrap programs on GPT disks.
It defaults to installing the wrong program.
[.filename]#/boot/mbr# expects the old MBR partition table layout.
The correct program for GPT disks is [.filename]#/boot/pmbr#.
====

=== On BIOS machines with MBR partition table disks

On BIOS machines with MBR partition table disks, there are even more stages, and an old rather confusing stage numbering system, that does not apply to UEFI and GPT:

. The BIOS loads and runs the MBR from its well-known place on the first (according to the BIOS) disk.
  For historical reasons, this is known as "stage 0".
  Sometimes there is a "stage 0.5".
. The MBR program reads the MBR Partition Table and picks the boot partition.
. The MBR program reads (only) the VBR from the boot partition and runs that.
. The VBR is the first part (known for historical reasons as "stage 1") of the next boot program:
.. On FreeBSD UFS partitions, this is man:boot[8].
.. On FreeBSD ZFS partitions, this is man:zfsboot[8].
. man:boot[8] or man:zfsboot[8] reads its second part (known for historical reasons as "stage 2") from the same boot partition.
. The "stage 1 and 2" boot program loads the loader:
.. man:boot[8] loads and runs man:loader[8] from the [.filename]#/boot# directory in the boot partition.
.. man:zfsboot[8] looks for FreeBSD ZFS partitions, looks at their zpool(s), reads the `bootfs` property of the zpool, and loads and runs man:zfsloader[8] from the [.filename]#/boot# directory in the named ZFS dataset.
. The man:loader[8] or man:zfsloader[8] program loads and runs the FreeBSD kernel.

[[boot-boot0]]
==== Stage 0

There are several programs that can be chosen for "stage 0".

The [.filename]#/boot/mbr# program is very basic, and is like the simple programs that other operating system install in the same place.
It simply selects the first "active" partition in the table, and selects that as the boot partition.
The size and capability of [.filename]#/boot/mbr# is restricted to 446 bytes due to the embedded (primary) partition table, the `0x55AA` identifier at the end of the MBR, and possibly even a Windows NT disk ID.

[.filename]#/boot/boot0# is a 2-stage "stage 0" that presents less terse information to the operator, at the expense of not fitting into a single boot record and having to load itself in 2 parts.
(This is sometimes known by the name 'Boot Easy'.)
[.filename]#/boot/boot0sio# is a version of [.filename]#/boot/boot0# that uses the serial port to interact with the operator, rather than the keyboard and screen.

If [.filename]#/boot/boot0# and multiple operating systems are installed, a message similar to this example will be displayed at boot time:

[[boot-boot0-example]]
.[.filename]#boot0# Screenshot
[example]
====

[source,shell]
....
F1 Win
F2 FreeBSD

Default: F2
....

====

The [.filename]#/boot/boot0# program and its variants are customizable.
To create a custom configuration of one of these, use man:boot0cfg[8].

The programs here are put into place by the FreeBSD installer.
Other operating systems will overwrite an existing MBR program if they are installed after FreeBSD.
They often will just do the same thing as [.filename]#/boot/mbr#.

To re-install one of the other MBR programs manually, if their functionality is required instead, use the `bootstrap` subcommand of the man:gpart[8] command.
Copies of the programs exist in the FreeBSD filesystem as files in the [.filename]#/boot# directory.

For example, supposing that the first BIOS disk is device [.filename]#ada0#, the first ATA (a.k.a. IDE) disk:
[source,shell]
....
# gpart bootstrap -b /boot/boot0 ada0
....
It would be [.filename]#ad2# for the first IDE disk on a second IDE controller, or [.filename]#da0# for the first SCSI disk, and so forth.

The older man:fdisk[8] command can be used instead:
[source,shell]
....
# fdisk -B -b /boot/boot0 device
....

[WARNING]
====
Although it has a similar looking name, [.filename]#/boot/pmbr# expects the GUID Partition Table, and is not for use on MBR partition table disks.
====

[[boot-boot1]]
==== Stage One and Stage Two

Conceptually, the first and second stages are part of the same program on the same area of the disk.
Due to space constraints, they have been split into two, but are always installed together.
They are copied from the combined [.filename]#/boot/boot# by the FreeBSD installer or `bsdlabel`.

These two stages are located outside file systems, in the first track of the boot slice, starting with the first sector.
This is where boot0, or any other MBR program (even one from another operating system), expects to find a program to run which will continue the boot process.

The first stage, [.filename]#boot1#, is very simple, since it can only be 512 bytes in size.
It knows just enough about the slice that it is in (a FreeBSD _bsdlabel_, which stores information about the slice, or just a plain old UFS partition in an MBR partition table) to find and execute [.filename]#boot2#.

Stage two, [.filename]#boot2#, is slightly more sophisticated, and understands the FreeBSD file system enough to find files.
It can provide a simple interface to choose the kernel or loader to run.
It runs loader, which is much more sophisticated and provides a boot configuration file.
If the boot process is interrupted at stage two, the following interactive screen is displayed:

[[boot-boot2-example]]
.[.filename]#boot2# Screenshot
[example]
====

[source,shell]
....
>> FreeBSD/i386 BOOT
Default: 0:ad(0,a)/boot/loader
boot:
....

====

For example, supposing that the first BIOS disk is device [.filename]#ada0#, the UFS root partition is (MBR) partition number 1 on that disk, and FreeBSD proper is installed in a UFS partition:
[source,shell]
....
# gpart bootstrap -p /boot/boot -i 1 ada0
....

[[boot-loader]]
=== The Loader

The loader is where the several variants of the FreeBSD bootstrap process come together and are largely the same.
It is located on the file system, as variously [.filename]#/boot/loader#, [.filename]#/boot/zfsloader#, or [.filename]#/boot/loader.efi#.

The loader is intended as an interactive method for configuration, using a built-in command set, backed up by a more powerful interpreter which has a more complex command set.

During initialization, loader will probe for a console and for disks, and figure out which disk it is booting from.
It will set variables accordingly, and an interpreter is started where user commands can be passed from a script or interactively.

The loader will then read [.filename]#/boot/loader.rc#, which by default reads in [.filename]#/boot/defaults/loader.conf# which sets reasonable defaults for variables and reads [.filename]#/boot/loader.conf# for local changes to those variables.
[.filename]#loader.rc# then acts on these variables, loading whichever modules and kernel are selected.

Finally, by default, loader issues a 10 second wait for key presses, and boots the kernel if it is not interrupted.
If interrupted, the user is presented with a prompt which understands the command set, where the user may adjust variables, unload all modules, load modules, and then finally boot or reboot.
crossref:boot[boot-loader-commands,Loader Built-In Commands] lists the most commonly used loader commands.
For a complete discussion of all available commands, refer to man:loader[8], man:zfsloader[8], and man:loader.efi[8].

[[boot-loader-commands]]
.Loader Built-In Commands
[cols="20%,80%", frame="none", options="header"]
|===
| Variable
| Description

|autoboot _seconds_
|Proceeds to boot the kernel if not interrupted within the time span given, in seconds. It displays a countdown, and the default time span is 10 seconds.

|boot [`-options`] [`kernelname`]
|Immediately proceeds to boot the kernel, with any specified options or kernel
name. Providing a kernel name on the command-line is only applicable after an
`unload` has been issued. Otherwise, the previously-loaded kernel will be
used. If _kernelname_ is not provided with the full path, it will be searched under _/boot/kernel_ and _/boot/modules_.

|boot-conf
|Goes through the same automatic configuration of modules based on specified variables, most commonly `kernel`. This only makes sense if `unload` is used first, before changing some variables.

|help [`_topic_`]
|Shows help messages read from [.filename]#/boot/loader.help#. If the topic given is `index`, the list of available topics is displayed.

|include `_filename_` ...
|Reads the specified file and interprets it line by line. An error immediately stops the `include`.

|load [-t ``_type_``] `_filename_`
|Loads the kernel, kernel module, or file of the type given, with the
specified filename. Any arguments after _filename_ are passed to the file. If
_filename_ is not provided with the full path, it will be searched under _/boot/kernel_ and _/boot/modules_.

|ls [-l] [``_path_``]
|Displays a listing of files in the given path, or the root directory, if the path is not specified. If `-l` is specified, file sizes will also be shown.

|lsdev [`-v`]
|Lists all of the devices from which it may be possible to load modules. If `-v` is specified, more details are printed.

|lsmod [`-v`]
|Displays loaded modules. If `-v` is specified, more details are shown.

|more `_filename_`
|Displays the files specified, with a pause at each `LINES` displayed.

|reboot
|Immediately reboots the system.

|set `_variable_`, set `_variable=value_`
|Sets the specified environment variables.

|unload
|Removes all loaded modules.
|===

Here are some practical examples of loader usage.
To boot the usual kernel in single-user mode:

[source,shell]
....
 boot -s
....

To unload the usual kernel and modules and then load the previous or another, specified kernel:

[source,shell]
....
 unload
 load /path/to/kernelfile
....

Use the full path [.filename]#/boot/GENERIC/kernel# to refer to the default kernel that comes with an installation, or [.filename]#/boot/kernel.old/kernel#, to refer to the previously installed kernel before a system upgrade or before configuring a custom kernel.

Use the following to load the usual modules with another kernel.
Note that in this case it is not necessary to provide the full path, only the file name:

[source,shell]
....
unload
set kernel="mykernel"
boot-conf
....

To load an automated kernel configuration script:

[source,shell]
....
 load -t userconfig_script /boot/kernel.conf
....

[[boot-init]]
=== The kernel and the first application-mode process

Once the kernel is loaded by either loader or by boot2, which bypasses loader, it examines any boot flags and adjusts its behavior as necessary.
crossref:boot[boot-kernel,Kernel Interaction During Boot] lists the commonly used boot flags.
Refer to man:boot[8] for more information on the other boot flags.

[[boot-kernel]]
.Kernel Interaction During Boot
[cols="1,1", frame="none", options="header"]
|===
| Option
| Description

|`-a`
|During kernel initialization, ask for the device to mount as the root file system.

|`-C`
|Boot the root file system from a CDROM.

|`-s`
|Boot into single-user mode.

|`-v`
|Be more verbose during kernel startup.
|===

Once the kernel has finished booting, it passes control to the user process man:init[8], which is located at [.filename]#/sbin/init#, or the program path specified in the `init_path` variable in `loader`.
This is the first application-mode process and the final part of the boot process.

The boot sequence makes sure that the file systems available on the system are consistent.
If a UFS file system is not, and `fsck` cannot fix the inconsistencies, init drops the system into single-user mode so that the system administrator can resolve the problem directly.
Otherwise, the system boots into multi-user mode.

[[boot-singleuser]]
==== Single-User Mode

A user can specify this mode by booting with `-s` or by setting the `boot_single` variable in loader.
It can also be reached by running `shutdown now` from multi-user mode.
Single-user mode begins with this message:

[.programlisting]
....
Enter full pathname of shell or RETURN for /bin/sh:
....

If the user presses kbd:[Enter], the system will enter the default POSIX(R) shell.
To specify a different shell, input the full path to the shell.

Single-user mode is usually used to repair a system that will not boot due to an inconsistent file system or an error in a boot configuration file.
It can also be used to reset the `root` password when it is unknown.
These actions are possible as the single-user mode prompt gives full, local access to the system and its configuration files.
There is no networking in this mode.

While single-user mode is useful for repairing a system, it poses a security risk unless the system is in a physically secure location.
By default, any user who can gain physical access to a system will have full control of that system after booting into single-user mode.

If the system `console` is changed to `insecure` in [.filename]#/etc/ttys#, the system will first prompt for the `root` password before initiating single-user mode.
This adds a measure of security while removing the ability to reset the `root` password when it is unknown.

[[boot-insecure-console]]
.Configuring an Insecure Console in [.filename]#/etc/ttys#
[example]
====
[.programlisting]
....
# name  getty                           type    status          comments
#
# If console is marked "insecure", then init will ask for the root password
# when going to single-user mode.
console none                            unknown off insecure
....

====

An `insecure` console means that physical security to the console is considered to be insecure, so only someone who knows the `root` password may use single-user mode.

[[boot-multiuser]]
==== Multi-User Mode

If init finds the file systems to be in order, or once the user has finished their commands in single-user mode and has typed `exit` to leave single-user mode, the system enters multi-user mode, in which it starts the resource configuration of the system.

The resource configuration system reads in configuration defaults from [.filename]#/etc/defaults/rc.conf# and system-specific details from [.filename]#/etc/rc.conf#.
It then proceeds to mount the system file systems listed in [.filename]#/etc/fstab#.
It starts up networking services, miscellaneous system daemons, then the startup scripts of locally installed packages.

To learn more about the resource configuration system, refer to man:rc[8] and examine the scripts located in [.filename]#/etc/rc.d#.

[[device-hints]]
== Device Hints

During initial system startup, the boot man:loader[8] reads man:device.hints[5].
This file stores kernel boot information known as variables, sometimes referred to as "device hints".
These "device hints" are used by device drivers for device configuration.

Device hints may also be specified at the loader prompt, as
demonstrated in crossref:boot[boot-loader, Stage Three].
Variables can be added using `set`, removed with `unset`, and viewed `show`.
Variables set in [.filename]#/boot/device.hints# can also be overridden.
Device hints entered at the boot loader are not permanent and will not be applied on the next reboot.

Once the system is booted, man:kenv[1] can be used to dump all of the variables.

The syntax for [.filename]#/boot/device.hints# is one variable per line, using the hash "#" as comment markers.
Lines are constructed as follows:

[source,shell]
....
 hint.driver.unit.keyword="value"
....

The syntax for the Stage 3 boot loader is:

[source,shell]
....
 set hint.driver.unit.keyword=value
....

where `driver` is the device driver name, `unit` is the device driver unit number, and `keyword` is the hint keyword.
The keyword may consist of the following options:

* `at`: specifies the bus which the device is attached to.
* `port`: specifies the start address of the I/O to be used.
* `irq`: specifies the interrupt request number to be used.
* `drq`: specifies the DMA channel number.
* `maddr`: specifies the physical memory address occupied by the device.
* `flags`: sets various flag bits for the device.
* `disabled`: if set to `1` the device is disabled.

Since device drivers may accept or require more hints not listed here, viewing a driver's manual page is recommended.
For more information, refer to man:device.hints[5], man:kenv[1], man:loader.conf[5], and man:loader[8].

[[boot-shutdown]]
== Shutdown Sequence

Upon controlled shutdown using man:shutdown[8], man:init[8] will attempt to run the script [.filename]#/etc/rc.shutdown#, and then proceed to send all processes the `TERM` signal, and subsequently the `KILL` signal to any that do not terminate in a timely manner.

To power down a FreeBSD machine on architectures and systems that support power management, use `shutdown -p now` to turn the power off immediately.
To reboot a FreeBSD system, use `shutdown -r now`.
One must be `root` or a member of `operator` in order to run man:shutdown[8].
One can also use man:halt[8] and man:reboot[8].
Refer to their manual pages and to man:shutdown[8] for more information.

Modify group membership by referring to crossref:basics[users-synopsis,“Users and Basic Account Management”].

[NOTE]
====
Power management requires man:acpi[4] to be loaded as a module or statically compiled into a custom kernel.
====
